version: '3'

services:
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - foodbank

  frontend:
    image: foodbank-client
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - AUTH_HOST=${AUTH_HOST}
      - AUTH_PORT=${AUTH_PORT}
    volumes:
      - letsencrypt-data:/home/letsencrypt/data
      - letsencrypt-certs:/home/letsencrypt/certs
    networks:
      - foodbank

  backend:
    depends_on:
      - mysql
    build: ./
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - AUTH_SERVER_BASE_URL=${AUTH_SERVER_BASE_URL}
      - DATASOURCE_USERNAME=${MYSQL_USER}
      - DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - foodbank

  keycloak:
    depends_on:
      - mysql
    build:
      context: ./docker/keycloak
      args:
        - REDIRECT_URIS=${REDIRECT_URIS}
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_PORT=${MYSQL_PORT}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "8083:8080"
      - "8787:8787"
    environment:
      - DEBUG_PORT=*:8787
      - DEBUG=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/import/realm/foodbank-realm.json
    networks:
      - foodbank

networks:
  foodbank:
    name: foodbank-network

volumes:
  mysql-data:
  letsencrypt-data:
  letsencrypt-certs: